### ISSUE TITLE
Bank Withdraw does not work

### ISSUE THREAD

**Issue by Clarebedo** [MarcTowler/ItsLit-RPG-Tracker#131]

**Comment by MarcTowler** [comment]
```
[14-Apr-2020 10:54:07 Europe/London] PHP Notice:  Undefined variable: flag in /home/marctowl/gapi.itslit.uk/src/Application/Model/BankModel.php on line 68
[14-Apr-2020 10:54:07 Europe/London] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /home/marctowl/gapi.itslit.uk/src/Application/Model/BankModel.php:71
Stack trace:
#0 /home/marctowl/gapi.itslit.uk/src/Application/Model/BankModel.php(71): PDOStatement->execute(Array)
#1 /home/marctowl/gapi.itslit.uk/src/Application/Controllers/Bank.php(96): API\Model\BankModel->withdraw('131526180313628...', 1, '100')
#2 /home/marctowl/gapi.itslit.uk/src/index.php(32): API\Controllers\Bank->withdraw()
#3 {main}
  thrown in /home/marctowl/gapi.itslit.uk/src/Application/Model/BankModel.php on line 71
```
